### Create new User
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "Calus@gmail.com",
    "password": "3456789"
}

### Get currently sigined user
GET http://localhost:3000/auth/whoami

### signout user
POST http://localhost:3000/auth/signout

### Signin as in existing User
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "Calus@gmail.com",
    "password": "3456789"
}

### Find a particular user with a given id
GET http://localhost:3000/auth/8

### Find all users with a given email
GET http://localhost:3000/auth?email=Chimz@gmail.com

### Delete a user given id
DELETE http://localhost:3000/auth/3

### Update a user
PATCH http://localhost:3000/auth/6
content-type: application/json

{
    "password": "qwergh"
}

# ### Set a color
# GET http://localhost:3000/auth/colors/red

# ### Get the color
# GET http://localhost:3000/auth/colors